# --- Server Configuration ---
server.port=8080
spring.threads.virtual.enabled=true

# --- Database Configuration (MongoDB) ---
spring.data.mongodb.uri=mongodb+srv://copa:Dia1133Cm9172@cluster0.6jrwunr.mongodb.net/db_1erP?appName=Cluster0
# --- JSON Strategy ---
# Se comenta para usar el default (LOWER_CAMEL_CASE) y coincidir con Angular
# spring.jackson.property-naming-strategy=SNAKE_CASE

# --- Security & JWT ---
# Importante: Cambiar este secreto en producción
application.security.jwt.secret-key=7b232aafc13a7292da663d2e51a4dd87d810a585b5ebc033c4dd76c36ef9d854
application.security.jwt.expiration=86400000
